reduce code
List-KR/jsdelivr-purge pull request #1
Opened 2023-03-11 12:31 UTC by green1052

1. 
![image](https://user-images.githubusercontent.com/34261355/224484544-4575dd01-5e7e-4478-aeaf-44823eff0c2b.png)

2. https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Arrow_functions
 
3. L#16 Actions.ExitCode를 return 해야하지 않나요?

2023-03-11 12:37 UTC, green1052 commented
추가로 threads.ts#L25, L26은 차라리 ChangedFiles 배열을 돌게하고
if문으로 체크하는게 좋을거 같아요 굳이 2번 배열을 돌 필요가 없어 보이네요

2023-03-12 09:34 UTC, piquark6046 requested changes

2023-03-12 09:34 UTC, piquark6046 commented on main.ts
> +${Branches.join(" - ")}
이렇게 GitHub workflow 로그에 기록되길 원하기에 `Array.prototype.map`을 사용했습니다.
```
  - asdf
  - 6534
  - 1234
```

2023-03-12 09:34 UTC, piquark6046 commented on main.ts
> +Branches.forEach((Branche, Index) => {
오류가 발생했을 때 디버깅하기에는 `Arrow function` 보다는 지금 사용 중인 표현이 더 낫습니다.

2023-03-12 09:34 UTC, piquark6046 commented on main.ts
> +    if (!BrancheThreads.length) { return Actions.ExitCode }
이거는 괜찮네요.
나중에 새 PR을 남겨주세요.

2023-03-12 09:37 UTC, green1052 commented on main.ts
> +${Branches.join(" - ")}
.join("\n- ")

2023-03-12 09:38 UTC, green1052 commented on main.ts
> +Branches.forEach((Branche, Index) => {
화살표 함수는 this만 달라지는걸로 아는데
무슨 디버깅 말씀하시는건가요

2023-03-12 09:45 UTC, piquark6046 commented on main.ts
> +${Branches.join(" - ")}
```typescript
${Branches.join('\n  - ').replace(/^\n /, '')}
```
이 코드가 더 나아 보이는데요.

2023-03-12 09:50 UTC, piquark6046 commented on main.ts
> +Branches.forEach((Branche, Index) => {
잘못된 정보였네요. 알겠습니다.

2023-03-12 09:54 UTC, green1052 commented on main.ts
> +${Branches.join(" - ")}
????????

2023-03-12 10:04 UTC, green1052 commented on main.ts
> +${Branches.join(" - ")}
그럼 그냥 map으로 하는게 낫겠네요
- ${Branches.join('\n  - ')}
보다는

2023-03-12 10:08 UTC, green1052 commented on main.ts
> +${Branches.join(" - ")}
+ new Array는 비권장되는 방법임으로
[1,2] 같이 하시는게 좋읍니다.

2023-03-12 10:09 UTC, piquark6046 commented on main.ts
> +${Branches.join(" - ")}
네. 닫겠습니다.

2023-03-12 10:30 UTC, piquark6046 approved these changes

2023-03-12 10:33 UTC, merged